# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventMapper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "Alamofire"
  pod "RxSwift"

  target 'EventMapperTests' do
    inherit! :search_paths
    pod "Quick"
    pod "Nimble"
  end

  target 'EventMapperUITests' do
  end

end
